[package]
name = "rust-binary-metafile-template"
description = ""
version = "0.1.0"
license = "MIT"
repository = "https://github.com/EdJoPaTo/rust-binary-metafile-template"
authors = ["EdJoPaTo <rust-binary-metafile-template-rust@edjopato.de>"]
edition = "2018"
rust-version = "1.48.0" # Debian 11

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# See https://doc.rust-lang.org/rustc/codegen-options/index.html
codegen-units = 1
lto = true

[build-dependencies]
clap = "2"

[dependencies]

[dependencies.clap]
version = "2"
features = ["wrap_help"]
