name: Update Arch Linux User Repository (AUR)

on:
  push:
    tags:
      - v*

jobs:
  aur-publish:
    name: AUR ${{ matrix.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        name:
          - rust-binary-metafile-template
          - rust-binary-metafile-template-bin
    steps:
      - uses: EdJoPaTo/update-aur-package-github-action@main
        with:
          package_name: ${{ matrix.name }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
