name: Test Coverage

on:
  push:
  pull_request:

jobs:
  tarpaulin:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Rust
        shell: bash -eux {0}
        run: |
          rustup --version
          rustup show
          rustup toolchain install stable --profile minimal
          rustup default stable

      - uses: actions/checkout@v3

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: --all-features
          out-type: Html

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: tarpaulin-report.html
