name: Test and Build Rust

on:
  push:
  pull_request:

jobs:
  test:
    name: Test ${{ matrix.toolchain }} ${{ matrix.os }} ${{ matrix.features }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
        os:
          - ubuntu-22.04
          - macos-12
          - windows-2022
        clippyargs:
          - -D clippy::pedantic -D warnings
        features:
          - --no-default-features
          - "" # default features
          - --all-features
        include:
          # Check future versions and maybe get some glances on soon to be lints
          - toolchain: beta
            os: ubuntu-22.04
            features: --all-features
            clippyargs: -W clippy::pedantic -W clippy::nursery -W clippy::cargo
          - toolchain: nightly
            os: ubuntu-22.04
            features: --all-features
            clippyargs: -W clippy::pedantic

          # Check the minimum supported Rust version (MSRV).
          # Sometimes old rust versions don't yet have the lints (allow unknown) or don't have fixes in lints (false positives -> don't error, just warn).
          # When a certain distro is a target look up its version: https://repology.org/project/rust/versions
          - os: ubuntu-22.04
            toolchain: 1.56.1
            clippyargs: -A unknown-lints
            features: --all-features
    steps:
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: true
          profile: minimal
          toolchain: ${{ matrix.toolchain }}

      - uses: actions/checkout@v3

      - name: Fetch dependencies
        uses: actions-rs/cargo@v1
        with:
          command: fetch
          args: --verbose --locked

      - name: Check clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose --locked --all-targets ${{ matrix.features }} -- ${{ matrix.clippyargs }}

      - name: Check docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --verbose --locked --no-deps ${{ matrix.features }}

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --locked ${{ matrix.features }}

  github-release:
    name: Release ${{ matrix.triple }}
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - triple: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            features: --all-features
            rpm: true
          - triple: aarch64-unknown-linux-gnu
            os: ubuntu-22.04
            features: --all-features
            rpm: true
          - triple: armv7-unknown-linux-gnueabihf
            os: ubuntu-22.04
            features: --all-features
            rpm: true
          - triple: arm-unknown-linux-gnueabihf
            os: ubuntu-22.04
            features: --all-features
          - triple: riscv64gc-unknown-linux-gnu
            os: ubuntu-22.04
            # https://github.com/briansmith/ring/issues/1419
            features: --no-default-features

          - triple: x86_64-apple-darwin
            os: macos-12
            features: --all-features
          - triple: aarch64-apple-darwin
            os: macos-12
            features: --all-features

          - triple: x86_64-pc-windows-msvc
            os: windows-2022
            features: --all-features
          - triple: aarch64-pc-windows-msvc
            os: windows-2022
            # https://github.com/briansmith/ring/issues/1167
            features: --no-default-features
    steps:
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          target: ${{ matrix.triple }}
          toolchain: stable

      - name: Setup deb tools
        if: runner.os == 'Linux'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb
      - name: Setup rpm tools
        if: matrix.rpm
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-generate-rpm

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set artifact name
        shell: bash
        run: |
          version="$(git describe --tags --match "v*.*.*" --always)"
          echo "version: $version"
          echo "GIT_TAG_VERSION=$version" >> $GITHUB_ENV

          name="rust-binary-metafile-template-$version-${{ matrix.triple }}"
          echo "artifact: $name"
          echo "ARTIFACT_NAME=$name" >> $GITHUB_ENV

      - name: Fetch dependencies
        uses: actions-rs/cargo@v1
        with:
          command: fetch
          args: --verbose --locked

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose --locked ${{ matrix.features }} --target ${{ matrix.triple }}
          use-cross: ${{ runner.os == 'Linux' && matrix.triple != 'x86_64-unknown-linux-gnu' }}

      - name: Package tar.gz (*nix)
        if: runner.os != 'Windows'
        run: >
          tar -cv
          LICENSE README.md
          systemd
          -C target/ completions/ -C ../
          -C target/${{ matrix.triple }}/release/ rust-binary-metafile-template
          | gzip --best > ${{ env.ARTIFACT_NAME }}.tar.gz
      - name: Package zip (Windows)
        if: runner.os == 'Windows'
        run: >
          7z a ${{ env.ARTIFACT_NAME }}.zip
          LICENSE README.md
          ./target/completions/
          ./target/${{ matrix.triple }}/release/rust-binary-metafile-template.exe
      - name: Package deb
        if: runner.os == 'Linux'
        run: cargo deb --verbose --no-build --no-strip --target ${{ matrix.triple }} --output ${{ env.ARTIFACT_NAME }}.deb
      - name: Package rpm
        if: matrix.rpm
        run: cargo generate-rpm --auto-req no --target ${{ matrix.triple }} --output ${{ env.ARTIFACT_NAME }}.rpm

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.triple }}
          path: |
            *.deb
            *.rpm
            *.tar.gz
            *.zip

      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
            *.rpm
            *.tar.gz
            *.zip

  aur-publish:
    name: AUR ${{ matrix.name }}
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-22.04
    needs: github-release
    strategy:
      fail-fast: false
      matrix:
        name:
          - rust-binary-metafile-template
          - rust-binary-metafile-template-bin
    steps:
      - uses: ATiltedTree/create-aur-release@v1
        with:
          package_name: ${{ matrix.name }}
          commit_username: GitHub Actions
          commit_email: rust-binary-metafile-template-github-actions@edjopato.de
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}

# TODO: more releases. Inspiration:
# https://github.com/starship/starship/blob/master/.github/workflows/deploy.yml
